In [58]:
####Simulation of the dataset####
import numpy as np
import pandas as pd

sample_size = 3000

df = pd.DataFrame({
    'roomMin': np.random.sample(sample_size),
    'roomMax': np.random.sample(sample_size),
    'priceMin': np.random.sample(sample_size),
    'priceMax': np.random.sample(sample_size)})

In [59]:
#####Modifying the complete simulated dataset#####

#percentage missing
#a for roomMin, b for roomMax, c for priceMin, d for priceMax
a = 0.23
b = 0.61
c = 0.69
d = 0.21

#create the 'missingness matrix'
df_NaN = pd.DataFrame({'NaN1' : np.random.sample(len(df)),
                       'NaN2' : np.random.sample(len(df)),
                       'NaN3' : np.random.sample(len(df)),
                       'NaN4' : np.random.sample(len(df))})

#transform the random values (uniform dist from 0 to 1) into integers referring to the missingness fraction
df_NaN.loc[(df_NaN.NaN1 <= a), 'NaN1'] = 0
df_NaN.loc[(df_NaN.NaN1 > a), 'NaN1'] = 1

df_NaN.loc[(df_NaN.NaN2 <= b), 'NaN2'] = 0
df_NaN.loc[(df_NaN.NaN2 > b), 'NaN2'] = 1

df_NaN.loc[(df_NaN.NaN3 <= c), 'NaN3'] = 0
df_NaN.loc[(df_NaN.NaN3 > c), 'NaN3'] = 1

df_NaN.loc[(df_NaN.NaN4 <= d), 'NaN4'] = 0
df_NaN.loc[(df_NaN.NaN4 > d), 'NaN4'] = 1

#multiply the missingness matrix with the dataset
df_with_missing = pd.DataFrame(df.values*df_NaN.values, columns=df.columns, index=df.index)

#remove rows where roomMin and roomMax or priceMin and priceMax are missing
Z = np.where((df_with_missing[df_with_missing.columns[0]] + df_with_missing[df_with_missing.columns[1]]==0) | (df_with_missing[df_with_missing.columns[2]] + df_with_missing[df_with_missing.columns[3]]==0))
Z1 = df_with_missing.drop(Z[0])
df_new = Z1.reset_index(drop = True)

#transform the 0 into NaN
df_new.loc[(df_new.roomMin == 0),'roomMin']= np.nan
df_new.loc[(df_new.roomMax == 0),'roomMax']= np.nan
df_new.loc[(df_new.priceMin == 0),'priceMin']= np.nan
df_new.loc[(df_new.priceMax == 0),'priceMax']= np.nan
df_new

       roomMin   roomMax  priceMin  priceMax
0     0.806130       NaN       NaN  0.139489
1     0.267024  0.946995  0.046715  0.575522
2     0.318501       NaN  0.624068       NaN
3          NaN  0.583810       NaN  0.533505
4     0.872774  0.350699       NaN  0.015707
...        ...       ...       ...       ...
2207  0.343758       NaN       NaN  0.905957
2208  0.041254       NaN       NaN  0.469073
2209  0.506194  0.147122  0.938868  0.381270
2210       NaN  0.471728  0.307257  0.156349
2211  0.362737  0.824118       NaN  0.225800

[2212 rows x 4 columns]

In [60]:
#####Preparing data for performance testing and iterative imputation#####
import random
seed = 30
np.random.seed(seed)
#splitting the dataset into two subsets
#df1 is for final performance testing (10% of the whole dataset); splitted into df1_store (5% of df1) for later comparison
#and df1_test (95% of df1) for actual actual performance testing
#df2 is for training and testing (90% of the whole dataset)
msk1 = np.random.rand(len(df_new)) < 0.1
df1 = df_new[msk1]
np.random.seed(seed + 1)
msk1_1 = np.random.rand(len(df1)) < 0.05
df1_store = df1[msk1_1]
df1_test = df1[~msk1_1]
df2 = df_new[~msk1]

#removing all rows with missing values in df2 (D0 in paper)
df2_full = df2.dropna()
np.random.seed(seed + 2)
#splitting into test (df2_test, D0,2 in paper) (20%) and training (df2_train, D0,1 in paper) (80%) set
msk2 = np.random.rand(len(df2_full)) < 0.8
df2_train = df2_full[msk2]
df2_test = df2_full[~msk2]
np.random.seed(seed + 3)
#second missingness matrix to determine which values from the test dataset (D0,2) to remove 
#to have the same missingness pattern
df_NaN2 = pd.DataFrame({'NaN1' : np.random.sample(len(df2_test)),
                        'NaN2' : np.random.sample(len(df2_test)),
                        'NaN3' : np.random.sample(len(df2_test)),
                        'NaN4' : np.random.sample(len(df2_test))})

df_NaN2.loc[(df_NaN2.NaN1 <= a), 'NaN1'] = 0
df_NaN2.loc[(df_NaN2.NaN1 > a), 'NaN1'] = 1

df_NaN2.loc[(df_NaN2.NaN2 <= b), 'NaN2'] = 0
df_NaN2.loc[(df_NaN2.NaN2 > b), 'NaN2'] = 1

df_NaN2.loc[(df_NaN2.NaN3 <= c), 'NaN3'] = 0
df_NaN2.loc[(df_NaN2.NaN3 > c), 'NaN3'] = 1

df_NaN2.loc[(df_NaN2.NaN4 <= d), 'NaN4'] = 0
df_NaN2.loc[(df_NaN2.NaN4 > d), 'NaN4'] = 1

#multiply the missingness matrix with the dataset
#df2_test_v1 (D0,2 mod in paper) is the test data set with the same missingness pattern as the original dataset (D in paper)
df2_test_v1 = pd.DataFrame(df2_test.values*df_NaN2.values, columns=df2_test.columns, index=df2_test.index)


#remove rows where roomMin and roomMax or priceMin and priceMax are missing and keeping the index
Y = df2_test_v1[(df2_test_v1[df2_test_v1.columns[0]] + df2_test_v1[df2_test_v1.columns[1]]==0) | (df2_test_v1[df2_test_v1.columns[2]] + df2_test_v1[df2_test_v1.columns[3]]==0)]
df2_test_new = df2_test_v1.drop(Y.index)

#transform the 0 into NaN
df2_test_new.loc[(df2_test_new.roomMin == 0),'roomMin']= np.nan
df2_test_new.loc[(df2_test_new.roomMax == 0),'roomMax']= np.nan
df2_test_new.loc[(df2_test_new.priceMin == 0),'priceMin']= np.nan
df2_test_new.loc[(df2_test_new.priceMax == 0),'priceMax']= np.nan

##at the beginning, there are already complete rows in the test set
##those rows have to added to the train set   
#dftest_complete contains the complete observations of the testset
indextoimpute_complete = df2_test_new[df2_test_new.isnull().sum(axis=1)!=0].index
index_incomplete = df2_test_new[df2_test_new.isnull().sum(axis=1)==0].index
dftest_complete = df2_test_new.drop(indextoimpute_complete)
#add it to the train set
df2_train = pd.concat([df2_full[msk2],dftest_complete])
#need another label for later iterations
df2_train_reset = pd.concat([df2_full[msk2],dftest_complete])
#update the test set
df2_test_new = df2_test_new.drop(index_incomplete)
#combination of df2_train and df2_test_new (for later performance testing)
df2_full1 = pd.concat([df2_train,df2_test_new])
df2_full_comp = df2_full.loc[df2_full1.index]

df2_test_new

       roomMin   roomMax  priceMin  priceMax
33    0.038320       NaN       NaN  0.172624
64    0.639170  0.293406       NaN  0.553020
76    0.939046  0.181441       NaN  0.719308
292   0.995801  0.840095       NaN  0.588574
367   0.237496       NaN       NaN  0.668920
543   0.392683       NaN       NaN  0.099204
590   0.795210       NaN       NaN  0.257124
1153  0.278960       NaN       NaN  0.821707
1188       NaN  0.536716  0.419711  0.995820
1200  0.523746       NaN       NaN  0.282085
1418  0.674559  0.081247       NaN  0.379269
1525  0.725638       NaN  0.765634  0.385289
1547  0.523593       NaN  0.647810  0.622112
1776  0.565225       NaN       NaN  0.097336
1828  0.541247       NaN       NaN  0.775494
1855  0.627090       NaN       NaN  0.184734
2117       NaN  0.214379       NaN  0.507926
2209  0.506194       NaN  0.938868  0.381270

In [61]:
#####K-Means Clustering#####

from sklearn.cluster import KMeans
min_clusters = 1
max_clusters = 5

#for the case we have division by zero
def division_0(n, d):
    return n / d if d else 0

#lists the NMSE (nomralized mean squared error) value for each run
NMSE_values_kmeans = []

i = 0
##imputing cluster centers into rows with i+1 missing values##
#shows which rows do not have i missing values (gives us an index)
indextoimpute = df2_test_new[df2_test_new.isnull().sum(axis=1)!=i+1].index
#we take the index from indextoimpute to get the dataframe with only i missing values (by dropping the rest)
dftest = df2_test_new.drop(indextoimpute)
dftest

       roomMin   roomMax  priceMin  priceMax
64    0.639170  0.293406       NaN  0.553020
76    0.939046  0.181441       NaN  0.719308
292   0.995801  0.840095       NaN  0.588574
1188       NaN  0.536716  0.419711  0.995820
1418  0.674559  0.081247       NaN  0.379269
1525  0.725638       NaN  0.765634  0.385289
1547  0.523593       NaN  0.647810  0.622112
2209  0.506194       NaN  0.938868  0.381270

In [62]:
##clustering##
#tells us which cells have missing values
missing = ~np.isfinite(dftest)
missing

      roomMin  roomMax  priceMin  priceMax
64      False    False      True     False
76      False    False      True     False
292     False    False      True     False
1188     True    False     False     False
1418    False    False      True     False
1525    False     True     False     False
1547    False     True     False     False
2209    False     True     False     False

In [63]:
#creating an array where each NaN=0 and each non-NaN keeps the value (transforms dataframe into an array)
imputation = np.where(missing, 0, dftest)
imputation

array([[0.63916955, 0.2934063 , 0.        , 0.55301999],
       [0.939046  , 0.18144071, 0.        , 0.71930809],
       [0.9958007 , 0.84009509, 0.        , 0.58857392],
       [0.        , 0.53671615, 0.4197113 , 0.9958196 ],
       [0.67455939, 0.08124653, 0.        , 0.37926947],
       [0.72563775, 0.        , 0.76563419, 0.3852891 ],
       [0.52359306, 0.        , 0.64780981, 0.62211174],
       [0.50619432, 0.        , 0.93886803, 0.38127029]])

In [64]:
#clusters the complete data
kmeans = KMeans(5, random_state=0).fit(df2_train)
result = kmeans.cluster_centers_
result

array([[0.20286604, 0.75595015, 0.63426287, 0.48532531],
       [0.37799468, 0.27855228, 0.46353712, 0.7818006 ],
       [0.77519404, 0.74513579, 0.33023797, 0.44566484],
       [0.74631206, 0.39170916, 0.72587825, 0.32523217],
       [0.19664318, 0.32685752, 0.31693845, 0.20930969]])

In [65]:
##finding the best cluster##

#array A contains all rows with i missing values
A = np.asarray(dftest)
#array B contains all clusters of one subset 
B = result
A

array([[0.63916955, 0.2934063 ,        nan, 0.55301999],
       [0.939046  , 0.18144071,        nan, 0.71930809],
       [0.9958007 , 0.84009509,        nan, 0.58857392],
       [       nan, 0.53671615, 0.4197113 , 0.9958196 ],
       [0.67455939, 0.08124653,        nan, 0.37926947],
       [0.72563775,        nan, 0.76563419, 0.3852891 ],
       [0.52359306,        nan, 0.64780981, 0.62211174],
       [0.50619432,        nan, 0.93886803, 0.38127029]])

In [91]:
A[7]

array([0.50619432,        nan, 0.93886803, 0.38127029])

In [66]:
#to store the arrays from the loop, will contain arrays with the manhattan distance of each row 
#to each cluster center
list = []
#loop: will go through all k rows with i+1 missing value
#calculating the distance: I will calculate the distance without prior imputation as it is easier and 
#the results are the same
#C calculates the distance, calculations with missing values result in 'NaN'
#D transforms 'NaN' in 0 and transforms the distance in absolute value
#finally, the manhattan distance is calculated by summarizing each array
for k in range(0,len(dftest)):
    C = A[k] - B
    D = np.absolute(np.nan_to_num(C))
    list.append(D.sum(axis=1, dtype='float'))

#this shows A[7]-result    
C

array([[ 0.30332828,         nan,  0.30460517, -0.10405502],
       [ 0.12819964,         nan,  0.47533092, -0.40053031],
       [-0.26899972,         nan,  0.60863006, -0.06439455],
       [-0.24011774,         nan,  0.21298978,  0.05603812],
       [ 0.30955114,         nan,  0.62192958,  0.1719606 ]])

In [67]:
D

array([[0.30332828, 0.        , 0.30460517, 0.10405502],
       [0.12819964, 0.        , 0.47533092, 0.40053031],
       [0.26899972, 0.        , 0.60863006, 0.06439455],
       [0.24011774, 0.        , 0.21298978, 0.05603812],
       [0.30955114, 0.        , 0.62192958, 0.1719606 ]])

In [92]:
#each value shows the distance to one cluster center
D.sum(axis=1, dtype='float')

array([0.71198847, 1.00406086, 0.94202433, 0.50914564, 1.10344133])

In [68]:
list

[array([0.96654205, 0.50480949, 0.69510913, 0.43323319, 0.8196879 ]),
 array([1.54467217, 0.72065539, 1.00119028, 0.79707831, 1.39781802]),
 array([0.9803282 , 1.3725755 , 0.45847505, 0.96121632, 1.69165931]),
 array([0.94427985, 0.51600868, 0.84804773, 1.12176137, 1.09914139]),
 array([1.25245282, 0.89640159, 0.83091927, 0.4362526 , 0.89348698]),
 array([0.75417925, 1.04625164, 0.54532824, 0.12048718, 1.15366973]),
 array([0.4710604 , 0.48955993, 0.74561972, 0.59766701, 1.07062329]),
 array([0.71198847, 1.00406086, 0.94202433, 0.50914564, 1.10344133])]

In [69]:
#list is containing n arrays with the manhattan distance to each cluster center
#the lowest value will be determined and 
#the number of the column (=label of the nearest cluster center) will be stored in an array (=E)
min_cols = lambda lst: [np.argmin(sublist) for sublist in lst]
E = np.asarray(min_cols(list))
E

array([3, 1, 2, 1, 3, 3, 0, 3], dtype=int64)

In [70]:
#result contains all clusters of one set
#result[E] contains an array which assigns each row one cluster 
#E assigns each missing value the nearest cluster
#result[[np.zeros(len(df2_test_new_iter),dtype=int)][missing] contains an array with all replaced values

#previously, imputation[missing] was the array with all missing values 
imputation[missing]

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [71]:
#in this step, this array is replaced by an array with the values of the cluster center
imputation[missing] = result[E][missing]
imputation[missing]

array([0.72587825, 0.46353712, 0.33023797, 0.37799468, 0.72587825,
       0.39170916, 0.75595015, 0.39170916])

In [72]:
#now, imputation contains the rows with replaced values (as array)
#creating a new dataframe from the results
#from array to dataframe
df2_test_new_imputed = pd.DataFrame(data = imputation,
                                    index = dftest.index,
                                    columns = dftest.columns)
df2_test_new_imputed

       roomMin   roomMax  priceMin  priceMax
64    0.639170  0.293406  0.725878  0.553020
76    0.939046  0.181441  0.463537  0.719308
292   0.995801  0.840095  0.330238  0.588574
1188  0.377995  0.536716  0.419711  0.995820
1418  0.674559  0.081247  0.725878  0.379269
1525  0.725638  0.391709  0.765634  0.385289
1547  0.523593  0.755950  0.647810  0.622112
2209  0.506194  0.391709  0.938868  0.381270

In [73]:
#before:
dftest

       roomMin   roomMax  priceMin  priceMax
64    0.639170  0.293406       NaN  0.553020
76    0.939046  0.181441       NaN  0.719308
292   0.995801  0.840095       NaN  0.588574
1188       NaN  0.536716  0.419711  0.995820
1418  0.674559  0.081247       NaN  0.379269
1525  0.725638       NaN  0.765634  0.385289
1547  0.523593       NaN  0.647810  0.622112
2209  0.506194       NaN  0.938868  0.381270

In [74]:
#df2_train before:
df2_train

       roomMin   roomMax  priceMin  priceMax
14    0.701960  0.833319  0.237742  0.424611
32    0.053835  0.484478  0.091098  0.035869
54    0.427319  0.246841  0.554329  0.763532
66    0.204375  0.394368  0.759124  0.241123
80    0.167977  0.985637  0.483044  0.297261
...        ...       ...       ...       ...
2173  0.994226  0.094804  0.817797  0.675035
2184  0.386802  0.532818  0.893985  0.387127
2196  0.057598  0.543319  0.487863  0.422560
1649  0.259612  0.042535  0.641751  0.912493
1651  0.383308  0.309885  0.242424  0.062084

[163 rows x 4 columns]

In [75]:
##adding the imputed data to the train set (D(i+1)_imp in paper, i+1 stands for the number of imputations)   
frames = [df2_train, df2_test_new_imputed]
df2_train = pd.concat(frames)
df2_train

       roomMin   roomMax  priceMin  priceMax
14    0.701960  0.833319  0.237742  0.424611
32    0.053835  0.484478  0.091098  0.035869
54    0.427319  0.246841  0.554329  0.763532
66    0.204375  0.394368  0.759124  0.241123
80    0.167977  0.985637  0.483044  0.297261
...        ...       ...       ...       ...
1188  0.377995  0.536716  0.419711  0.995820
1418  0.674559  0.081247  0.725878  0.379269
1525  0.725638  0.391709  0.765634  0.385289
1547  0.523593  0.755950  0.647810  0.622112
2209  0.506194  0.391709  0.938868  0.381270

[171 rows x 4 columns]

In [76]:
##calculating NMSE
#storing the NMSE value of each column and number of imputed values per observation
sqrterror = []

v=0
#mean of the variable (for each column; mu in paper)
mu = np.mean(df2_train_reset[df2_train_reset.columns[v]])
mu

0.4806551970208997

In [83]:
#splitting the NMSE calculation
nominator = (df2_full_comp[df2_full_comp.columns[v]] - df2_train[df2_train.columns[v]])**2
denominator = df2_test_new.isna().sum()[v]*mu
nominator.fillna(0)

14      0.0
32      0.0
33      0.0
54      0.0
64      0.0
       ...
2117    0.0
2173    0.0
2184    0.0
2196    0.0
2209    0.0
Name: roomMin, Length: 181, dtype: float64

In [85]:
#for the case that we have 0 replaced values in one column
F = division_0(nominator.fillna(0), denominator)
F

14      0.0
32      0.0
33      0.0
54      0.0
64      0.0
       ...
2117    0.0
2173    0.0
2184    0.0
2196    0.0
2209    0.0
Name: roomMin, Length: 181, dtype: float64

In [86]:
sqrterror.append(np.sum(F))
np.sum(F)

0.011264835757603413

In [87]:
NMSE = np.sum(sqrterror)
NMSE

0.011264835757603413

In [ ]:
#####################

In [403]:
#####OPTICS Clustering#####
from sklearn.cluster import OPTICS

#for the case we have division by zero
def division_0(n, d):
    return n / d if d else 0

#lists the NMSE (nomralized mean squared error) value for each run
NMSE_values_optics = []

#OPTICS "finds core sample of high density and expands clusters from them"
#We iterate over the number of samples in a neighborhood for a point to be considered as a core point (fraction of sample size)
#example: 10%: a point will considered as high density point if at least 10% of the sample is in the neighborhood
#each sample gets a label for a cluster, except for noisy samples

#loop for finding the best fraction of the sample for the lowest NMSE 
for clusters in range(1, 20):
    #loop for the multiple imputation process
    for n in range(0,5):
        #I have to reset the dataframe df2_train, otherwise it would cumulate over all iterations
        df2_train = df2_train_reset
        #loop for the iterative imputation process
        for i in range(0,2):

            ##imputing cluster centers into rows with i missing values##
            #shows which rows do not have i missing values (gives us an index)
            indextoimpute = df2_test_new[df2_test_new.isnull().sum(axis=1)!=i+1].index
            #we take the index from indextoimpute to get the dataframe with only i missing values (by dropping the rest)
            dftest = df2_test_new.drop(indextoimpute)


            ##clustering##
            #tells us which cells have missing values
            missing = ~np.isfinite(dftest)
            #creating an array where each NaN=0 and each non-NaN keeps the value (transforms dataframe into an array)
            imputation = np.where(missing, 0, dftest)
            #clusters the complete data
            clustering = OPTICS(min_samples = clusters/100).fit(df2_train)
            optics = clustering.labels_
            optics_clusters = []
            #iterate for each label
            for labels in range(0,np.max(optics)+1):
                #look for the samples with the same label
                a = np.where(optics==labels)
                #take the mean of the samples with the same label to get the center of the cluster
                b = np.sum(core_array, axis=0)/np.max(np.shape(a))
                #store the cluster center
                optics_clusters.append(b)

            ##finding the best cluster##

            #array A contains all rows with i missing values
            A = np.asarray(dftest)
            #array B contains all clusters of one subset 
            B = np.asarray(optics_clusters)
            #to store the arrays from the loop, will contain arrays with the manhattan distance of each row 
            #to each cluster center
            list = []
            #loop: will go through all k rows with i+1 missing value
            #calculating the distance: I will calculate the distance without prior imputation as it is easier and 
            #the results are the same
            #C calculates the distance, calculations with missing values result in 'NaN'
            #D transforms 'NaN' in 0 and transforms the distance in absolute value
            #finally, the manhatten distance is calculated by summarizing each array
            for k in range(0,len(dftest)):
                C = A[k] - B
                D = np.absolute(np.nan_to_num(C))
                list.append(D.sum(axis=1, dtype='float'))

            #list is containing n arrays with the manhattan distance to each cluster center
            #the lowest value will be determined and 
            #the number of the column (=label of the nearest cluster center) will be stored in an array (=E)
            min_cols = lambda lst: [np.argmin(sublist) for sublist in lst]
            E = np.asarray(min_cols(list))

            #optics_clusters contains all clusters of one set
            #optics_clusters[E] contains an array which assigns each row one cluster 
            #E assigns each missing value the nearest cluster
            #optics_clusters[[np.zeros(len(df2_test_new_iter),dtype=int)][missing] contains an array with all replaced values

            #previously, imputation[missing] was the array with all missing values 
            #in this step, this array is replaced by an array with the values of the cluster center
            imputation[missing] = np.asarray(optics_clusters)[E][missing]

            #now, imputation contains the rows with replaced values (as array)
            #creating a new dataframe from the results
            #from array to dataframe
            df2_test_new_imputed = pd.DataFrame(data = imputation,
                                                index = dftest.index,
                                                columns = dftest.columns)

            ##adding the imputed data to the train set (D(i+1)_imp in paper, i+1 stands for the number of imputations)   
            frames = [df2_train, df2_test_new_imputed]
            df2_train = pd.concat(frames)
                
        #saving the dataset of the multiple imputation run n
        J = df2_train
        #after the 2nd run (n == 1): add the new dataset (=J) to the old one (=I, from the first run)
        #K is the cumulated dataset                         
        if n == 1:
            K = I + J
        #after the 3rd run +: add to the cumulated dataset of the previous run, the new dataset J     
        if n > 1:
            K = K + J
        #saving the dataset for the next run            
        I = df2_train        



    #the complete dataset is the result of 5 imputation runs, the datasets were added previously
    #now they are divided by 5
    estimated_df2 = K/5
    estimated_df2

    ##calculating NMSE
    #storing the NMSE value of each column and number of imputed values per observation
    sqrterror = []

    #v: number of column
    for v in range(0,len(estimated_df2.columns)):
        #mean of the variable before imputation (for each column; mu in paper)
        mu = np.mean(df2_train_reset[df2_train_reset.columns[v]])
        #splitting the NMSE calculation
        nominator = (df2_full_comp[df2_full_comp.columns[v]] - estimated_df2[estimated_df2.columns[v]])**2
        denominator = df2_test_new.isna().sum()[v]*mu
        #for the case that we have 0 replaced values in one column
        F = division_0(nominator, denominator)
        sqrterror.append(np.sum(F))
    NMSE = np.sum(sqrterror)
    NMSE_values_optics.append(NMSE)
NMSE_values_optics

[3.311250609156523,
 1.374598395104716,
 0.7661155353867387,
 0.6940352368820923,
 1.3228945644829695,
 1.9754709283521197,
 0.981299106392588,
 1.9754709283521197,
 1.9754709283521197,
 1.9754709283521197,
 1.9754709283521197,
 1.9754709283521197,
 1.9754709283521197,
 1.9754709283521197,
 1.9754709283521197,
 1.9754709283521197,
 1.9754709283521197,
 1.9754709283521197,
 1.9754709283521197]

In [404]:
#####matrix factorization#####
from sklearn.decomposition import NMF

for components in range(1,7):
    matrix = NMF(n_components = components, init="random", random_state = 0)
    W = matrix.fit_transform(np.nan_to_num(df2_full1))
    H = matrix.components_
W.dot(H)

array([[5.38244833e-02, 4.84510856e-01, 9.11030875e-02, 3.58659407e-02],
       [3.82786385e-02, 3.96202422e-01, 6.29478635e-01, 1.72624892e-01],
       [6.39221879e-01, 2.93323852e-01, 7.25383943e-01, 5.52997578e-01],
       [1.68004561e-01, 9.85626872e-01, 4.83053772e-01, 2.97242543e-01],
       [4.81818219e-01, 9.77447872e-01, 6.25659463e-01, 8.76701676e-01],
       [8.52444669e-01, 3.51702640e-01, 3.36092330e-03, 4.36478726e-01],
       [2.08845836e-01, 2.79439693e-01, 4.58417353e-01, 9.20510940e-01],
       [1.04482132e-02, 6.69067225e-01, 3.92912756e-01, 3.50761487e-01],
       [8.69076667e-02, 2.13440189e-01, 6.70462682e-01, 6.66259136e-01],
       [4.69046555e-01, 5.31682463e-01, 9.85614578e-01, 4.04357274e-01],
       [2.09273620e-01, 3.16144907e-01, 5.42769534e-01, 4.70762273e-01],
       [8.15109241e-01, 1.52642121e-01, 8.14307682e-01, 3.60235183e-01],
       [4.61655887e-01, 6.40061566e-01, 5.03567107e-01, 2.38785191e-01],
       [2.76581167e-02, 2.07944862e-02, 4.89104676e-02, 3.19053702e-01],
       [1.26287307e-01, 4.64366698e-01, 8.54774390e-01, 5.47697246e-01],
       [9.96032753e-01, 8.40045546e-01, 7.70349110e-01, 5.88460577e-01],
       [4.03489930e-01, 2.13160354e-01, 2.16052805e-01, 6.49556802e-01],
       [6.75703707e-01, 4.06912323e-01, 9.16463679e-01, 5.92115922e-01],
       [4.41077403e-01, 9.67670860e-01, 4.07534127e-01, 7.19492619e-01],
       [2.37544550e-01, 9.89955390e-01, 9.22131099e-01, 6.68894240e-01],
       [4.41001541e-01, 2.79856620e-01, 7.62089999e-01, 2.20543895e-01],
       [1.41585181e-01, 9.48521997e-01, 2.25263854e-01, 4.90164731e-01],
       [9.57871208e-01, 2.63315431e-01, 6.77552378e-01, 3.09703776e-01],
       [2.29144470e-01, 3.65592591e-01, 8.39911432e-01, 5.49945371e-01],
       [6.86346230e-01, 5.49332560e-01, 4.07260336e-01, 5.04055782e-01],
       [7.10183679e-01, 8.36352482e-02, 4.58815302e-01, 7.65948669e-01],
       [2.47371373e-01, 8.99231131e-01, 8.90319051e-01, 5.17769196e-01],
       [3.97043612e-01, 1.19078513e-01, 1.14231794e-01, 9.82537846e-01],
       [9.60797936e-01, 3.35075172e-02, 5.86184058e-01, 4.75995085e-01],
       [8.22780285e-01, 4.62880519e-02, 1.58088380e-01, 3.75728878e-01],
       [9.63596814e-01, 7.63575772e-01, 7.39051327e-02, 4.77334954e-01],
       [3.89219521e-01, 7.13116409e-01, 7.14231162e-01, 3.43156722e-01],
       [1.81306214e-01, 3.39399080e-01, 3.92507344e-01, 4.38535619e-01],
       [7.82143114e-01, 8.24579547e-01, 7.85945844e-01, 3.57045363e-01],
       [3.92152101e-01, 5.99908417e-01, 6.69261991e-01, 9.92495064e-02],
       [9.27053851e-01, 8.09623175e-01, 2.02598835e-01, 1.20562651e-01],
       [1.41639637e-01, 3.01426892e-01, 1.63075727e-01, 6.70869208e-02],
       [7.95602486e-01, 8.17492710e-01, 5.41949517e-02, 2.57002105e-01],
       [8.39789657e-01, 6.56245893e-01, 3.43560528e-01, 6.31857508e-01],
       [1.90080648e-01, 1.90675638e-01, 6.49696189e-01, 1.44291965e-01],
       [9.47686633e-01, 3.73027826e-01, 3.56263469e-01, 6.53869154e-01],
       [7.31292269e-01, 7.34679855e-01, 3.06106009e-01, 7.42869634e-01],
       [7.27645423e-01, 9.96608923e-01, 2.32318049e-01, 6.17049741e-01],
       [5.07289898e-02, 5.67336094e-01, 2.62852925e-01, 3.47200785e-01],
       [1.03625917e-01, 7.52948006e-01, 8.86528904e-01, 8.88451311e-01],
       [7.42759091e-01, 6.10965733e-01, 5.39357918e-01, 6.78716022e-01],
       [3.73021146e-02, 5.17303015e-01, 2.87179950e-01, 2.50747847e-01],
       [9.70206900e-01, 5.94411723e-01, 7.17390193e-01, 6.22701716e-01],
       [1.45955669e-01, 9.09887812e-01, 4.30394636e-01, 7.81122107e-01],
       [6.75938011e-01, 6.91484037e-01, 2.35985682e-01, 4.63182562e-01],
       [5.74653575e-01, 6.90562603e-01, 3.69558170e-01, 3.42432643e-02],
       [8.94472673e-01, 7.79924357e-01, 9.69658160e-01, 2.58530205e-01],
       [7.51474942e-01, 7.76349644e-01, 2.34376827e-01, 1.62823655e-01],
       [4.66255271e-01, 1.27535329e-01, 5.40368810e-01, 7.19851657e-01],
       [1.42576957e-01, 3.43220769e-01, 1.64581573e-01, 1.24870460e-01],
       [2.83398391e-01, 1.08523701e-01, 3.78440026e-01, 6.76013117e-01],
       [2.86202027e-01, 7.86325191e-01, 7.76064862e-01, 5.43072209e-01],
       [8.50763338e-01, 4.25265275e-01, 4.76279218e-01, 2.22593422e-01],
       [3.05151124e-01, 8.88167523e-01, 7.88644749e-01, 8.62282711e-01],
       [1.05157122e-01, 8.82894553e-01, 8.67413210e-01, 2.67803989e-01],
       [6.58499368e-02, 8.28215423e-01, 6.60955857e-02, 4.15650691e-02],
       [4.11928088e-01, 2.98588234e-01, 7.73484508e-01, 7.88084498e-01],
       [3.57803969e-01, 5.95709405e-01, 4.98288831e-01, 8.30690023e-01],
       [9.85476367e-01, 6.13836185e-01, 7.31580857e-01, 2.20225529e-01],
       [8.76220606e-01, 2.76181602e-02, 6.79767285e-01, 6.85334477e-01],
       [7.03140863e-02, 5.11819377e-02, 5.22343377e-01, 3.24627714e-01],
       [3.64073867e-02, 7.08274064e-01, 9.27912224e-01, 2.34241232e-01],
       [3.05836052e-01, 3.32335035e-01, 5.22205751e-01, 2.73882627e-01],
       [2.18568360e-01, 2.91412944e-01, 6.17440136e-02, 6.61055306e-01],
       [5.17113398e-01, 4.31053830e-01, 7.71726206e-01, 1.73831271e-01],
       [3.90002396e-01, 9.40478853e-01, 9.99660536e-01, 1.36438901e-01],
       [7.36194173e-01, 9.36446152e-01, 8.83019597e-01, 4.36704786e-01],
       [6.69556221e-01, 8.24705010e-01, 5.61166070e-01, 5.75362598e-01],
       [8.57873329e-01, 2.59724673e-01, 9.77635867e-01, 1.59806971e-01],
       [2.83136241e-01, 3.31268500e-01, 6.85922918e-01, 6.30779761e-01],
       [4.47299280e-01, 5.73956122e-01, 4.36069898e-01, 3.83524472e-01],
       [9.87835279e-01, 3.03529145e-01, 5.49193125e-01, 7.26082903e-02],
       [1.01336353e-01, 9.55787535e-01, 4.03604727e-01, 4.80133844e-01],
       [8.25133617e-01, 7.26509939e-01, 6.62882143e-01, 1.30161949e-02],
       [2.79064924e-01, 6.53241160e-01, 2.47356521e-01, 8.21674221e-01],
       [1.91182439e-01, 3.86542371e-01, 1.05935290e-01, 5.11935569e-02],
       [2.74069455e-01, 5.36666545e-01, 4.19733116e-01, 9.95782055e-01],
       [5.22947613e-01, 2.50585088e-01, 9.27675927e-01, 2.82160282e-01],
       [2.47270394e-01, 3.50401465e-01, 1.26591161e-01, 1.53190819e-01],
       [5.40514546e-01, 2.98995822e-01, 7.52399297e-01, 1.32211233e-01],
       [7.33088775e-01, 3.00384573e-01, 2.72404661e-01, 9.05794976e-01],
       [6.56227219e-01, 2.20190152e-01, 6.36507395e-01, 3.92392643e-02],
       [4.40618989e-01, 2.65583743e-01, 9.44120910e-01, 1.34995421e-01],
       [8.78448167e-01, 5.47484337e-01, 7.19982097e-01, 7.45872513e-01],
       [5.25514617e-01, 5.97965025e-01, 8.34788210e-01, 4.45279578e-01],
       [9.11550220e-01, 1.55170381e-01, 8.30388130e-01, 8.99356371e-02],
       [3.74429757e-01, 1.92022309e-01, 7.34252611e-01, 5.82587648e-01],
       [6.11654299e-01, 4.89005483e-01, 6.33612321e-01, 4.60524250e-03],
       [5.35259011e-01, 3.57518676e-01, 4.75365804e-01, 9.97827895e-01],
       [6.73824525e-01, 8.12545884e-02, 8.82268165e-01, 3.79328258e-01],
       [3.57636005e-01, 6.93771578e-01, 3.07006881e-01, 8.68921539e-01],
       [7.37135204e-03, 4.17096804e-01, 2.32838371e-02, 6.71306801e-01],
       [2.67647620e-03, 4.64887028e-01, 6.05936168e-01, 5.33237716e-01],
       [1.49103045e-01, 8.15658211e-01, 4.69882725e-01, 2.09858580e-01],
       [1.27085188e-01, 7.72510970e-01, 4.16798124e-01, 2.87296003e-01],
       [6.66373806e-01, 1.79712771e-01, 8.58161211e-01, 4.40458869e-01],
       [5.75557109e-01, 1.18824281e-01, 4.72580947e-01, 1.89462375e-01],
       [6.55909310e-01, 3.33445541e-01, 9.31355976e-01, 7.21219603e-01],
       [1.43698651e-01, 5.06858742e-01, 3.76202840e-01, 7.47230090e-01],
       [7.25111549e-01, 3.54963638e-01, 7.65768806e-01, 3.85309095e-01],
       [5.69106740e-02, 1.85824200e-02, 3.61259815e-01, 7.34247492e-01],
       [1.36756123e-01, 9.33821149e-01, 9.19689854e-02, 9.93138547e-03],
       [5.23713116e-01, 7.68022724e-01, 6.47759464e-01, 6.22085562e-01],
       [8.90088563e-01, 7.02280334e-01, 3.49354688e-01, 3.23831800e-01],
       [3.78928224e-01, 8.77475076e-01, 2.35708618e-01, 9.24076300e-01],
       [6.98537339e-01, 3.90022910e-01, 5.08003965e-01, 1.63961644e-01],
       [4.28144645e-01, 1.01537289e-01, 1.43172121e-02, 9.63747972e-01],
       [6.07453459e-01, 3.07619916e-01, 5.01526483e-01, 2.55576922e-01],
       [3.03884160e-01, 9.14962746e-02, 1.48187974e-01, 3.07545367e-01],
       [2.58977285e-01, 4.25367771e-02, 6.41887474e-01, 9.12572096e-01],
       [3.83379052e-01, 3.09887327e-01, 2.42393304e-01, 6.20626552e-02],
       [4.19260021e-01, 3.68027977e-01, 2.23804105e-01, 3.19963249e-02],
       [1.06691776e-01, 7.59672335e-01, 5.89481481e-01, 5.37949439e-01],
       [6.48622685e-01, 2.21812029e-01, 2.14095784e-01, 9.36213734e-01],
       [5.04288941e-01, 6.19389828e-01, 7.03930436e-01, 8.26815312e-01],
       [4.95232666e-01, 2.45004506e-01, 2.88072235e-01, 9.73386431e-02],
       [7.24630099e-01, 9.92158872e-01, 4.73768950e-01, 2.77678998e-01],
       [3.31348713e-02, 9.19668178e-01, 7.76452574e-01, 1.21756839e-01],
       [4.23014936e-01, 2.31617778e-01, 9.92432503e-01, 3.22060684e-02],
       [8.26219267e-01, 4.37944708e-01, 7.35501361e-01, 2.70686836e-01],
       [5.65309152e-01, 8.45551532e-01, 1.68777041e-01, 9.72782319e-02],
       [3.27501273e-01, 3.16522065e-02, 3.22697501e-01, 9.11473060e-01],
       [6.23078863e-01, 5.24457476e-01, 6.43444473e-01, 8.46780549e-01],
       [6.70494245e-01, 4.64764952e-01, 7.01699806e-01, 5.27707945e-01],
       [5.62279053e-01, 7.37615508e-01, 8.43095672e-01, 5.63590740e-01],
       [5.41517585e-01, 2.68765328e-01, 4.25051567e-01, 7.75412476e-01],
       [5.03911348e-01, 4.90659436e-01, 6.03760748e-01, 1.18856634e-01],
       [8.11249701e-01, 2.62302300e-01, 5.46890633e-01, 8.63165960e-01],
       [8.98633213e-01, 9.51531855e-01, 7.21711415e-01, 6.22204832e-01],
       [6.26221206e-01, 2.09990693e-01, 9.72336543e-01, 1.84815225e-01],
       [1.18707782e-01, 2.67631069e-01, 7.01199059e-01, 3.04070166e-02],
       [9.44449795e-01, 9.49764540e-01, 6.40596347e-01, 3.22438529e-01],
       [4.98960104e-02, 5.04573818e-01, 8.20825217e-01, 5.72838988e-01],
       [8.90592094e-01, 4.94653122e-01, 6.68039336e-01, 7.72231753e-01],
       [5.69657262e-01, 3.58224101e-01, 2.36120704e-01, 1.22777503e-01],
       [2.52679060e-01, 1.32413746e-01, 8.03530489e-01, 3.71383568e-01],
       [7.06923760e-01, 9.37190833e-02, 7.76073870e-02, 7.95248339e-01],
       [5.08063721e-01, 4.31943710e-01, 5.57698969e-01, 8.26402712e-01],
       [1.78047295e-01, 8.08066972e-01, 4.58481059e-01, 1.34182620e-01],
       [9.40326160e-01, 5.91405950e-01, 5.04127904e-01, 9.61196701e-01],
       [5.36245651e-02, 2.73872507e-01, 8.24831960e-02, 9.29443692e-01],
       [1.89045470e-01, 8.13941762e-01, 2.77753456e-01, 7.77194977e-01],
       [6.01010585e-01, 6.45065788e-01, 5.49778976e-01, 9.18254558e-01],
       [7.00975911e-01, 2.70450719e-01, 5.14990334e-01, 8.60015640e-02],
       [7.33291733e-01, 6.34721981e-02, 8.14696790e-01, 2.66396910e-01],
       [8.26044383e-01, 8.64683890e-01, 9.46592444e-02, 1.52931651e-01],
       [3.32288016e-01, 9.81036333e-01, 7.55346725e-01, 8.43127466e-01],
       [5.21563973e-01, 7.08826754e-01, 8.83325645e-01, 2.98173873e-01],
       [3.04063581e-01, 1.17832049e-01, 5.71097290e-01, 5.73092783e-01],
       [8.65359751e-01, 9.69092125e-01, 1.68907006e-01, 2.71610594e-01],
       [9.62513177e-01, 2.14315712e-01, 9.74152166e-01, 5.07921317e-01],
       [9.93807535e-01, 9.47936364e-02, 8.17895536e-01, 6.75020990e-01],
       [1.38035402e-01, 1.88803665e-01, 5.79207493e-01, 5.17533935e-01],
       [5.05306404e-01, 1.47136065e-01, 9.39085438e-01, 3.81365909e-01],
       [7.02169315e-01, 8.33373683e-01, 2.37715701e-01, 4.24526101e-01],
       [6.84533258e-01, 2.19389539e-01, 2.46215457e-01, 5.81229430e-01],
       [2.29422855e-01, 4.63680471e-01, 6.27217679e-01, 7.67917383e-01],
       [8.00907366e-01, 5.84570847e-01, 8.40868424e-01, 8.76845125e-02],
       [4.27533192e-01, 0.00000000e+00, 1.16378073e-03, 7.63469502e-01],
       [2.04477287e-01, 0.00000000e+00, 3.51685537e-04, 2.41092300e-01],
       [4.62424288e-01, 2.90671165e-01, 1.19373906e-03, 7.86409009e-01],
       [1.65466525e-04, 9.99601783e-01, 5.94972872e-04, 3.60185906e-01],
       [8.50936094e-01, 2.15050887e-07, 2.21050647e-05, 1.30332650e-01],
       [8.44643122e-01, 2.46406254e-04, 3.38719589e-01, 6.47646079e-01],
       [1.13820973e-02, 0.00000000e+00, 9.55357229e-04, 5.79925210e-01],
       [9.08342954e-01, 0.00000000e+00, 5.63115432e-04, 4.66119455e-01],
       [3.02021913e-02, 0.00000000e+00, 1.14039175e-03, 6.94536229e-01],
       [4.95454677e-01, 0.00000000e+00, 1.19348003e-03, 7.90812231e-01],
       [9.87043170e-01, 0.00000000e+00, 1.02796105e-03, 7.58377859e-01],
       [6.21989937e-01, 1.08986176e-03, 6.29566790e-01, 7.83395847e-02],
       [4.79321612e-01, 3.39366103e-05, 2.79245805e-01, 6.41674100e-01],
       [1.24943693e-01, 0.00000000e+00, 5.76116833e-04, 3.65994891e-01]])